name: Build

on:
  push:
  pull_request:

jobs:
  assemble-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: :app:assembleDebug -x test --info --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
