name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: chmod +x ./gradlew
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: testDebugUnitTest --info --stacktrace